language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit-randomizer --order rand --bootstrap vendor/autoload.php tests
  - ./vendor/bin/phpcs --standard=phpcs.xml src/
